### ISSUE TITLE
[PE-D][Tester E] Flashbang command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-T11-2/tp#105]
Flashbang command does not work at all

![image.png](https://raw.githubusercontent.com/shyaamald/ped/main/files/204a4671-a9ea-40bf-b330-73adb072c63f.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: shyaamald/ped#5

**Comment by mikolajed** [comment]
Duplicated #99
