### ISSUE TITLE
[PE-D][Tester D] view_feature_bug: wrong set name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T11-2/tp#117]
![view_bug_wrong_set_name.png](https://raw.githubusercontent.com/Zackermax/ped/main/files/a7bc735d-5818-495c-be98-c41734baac4d.png)
When a view command is called, it prints the set name as "seedu.duke.flashutils.types.FlashCardSet@7daf6ecc". This does not seem to be the proper name of the set.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: Zackermax/ped#9

**Comment by mikolajed** [comment]
Duplicated #119
