### ISSUE TITLE
[PE-D][Tester A] Error in parsing commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T11-2/tp#130]
Adding a whitespace in front of the input result in invalid command error 

![image.png](https://raw.githubusercontent.com/KuanHsienn/ped/main/files/bb8946a6-cca7-41cc-88d6-12d76e7c1674.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: KuanHsienn/ped#8

**Comment by Paulifyer** [comment]
Fixed by trimming user inputs before parsing
