### ISSUE TITLE
[PE-D][Tester C] Handling of spaces

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T11-2/tp#138]
Adding additional spaces to the end of a module classifies it as a different module

![Screenshot 2024-11-08 at 17.04.41.png](https://raw.githubusercontent.com/Yisoong/ped/main/files/053141f1-8b03-4149-be8c-748c62e79aca.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Yisoong/ped#11

**Comment by mikolajed** [comment]
Resolved. 
<img width="472" alt="image" src="https://github.com/user-attachments/assets/53a3efa8-9b85-468c-a8c7-e4c0a41816dd">
