### ISSUE TITLE
[PE-D][Tester C] View with wrong comand

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T11-2/tp#143]
The view function works with a wrong command (in this case "viewview --m [MODULE NAME]")
![Screenshot 2024-11-08 at 17.09.10.png](https://raw.githubusercontent.com/Yisoong/ped/main/files/367f2ab6-14b7-4f9c-9b78-1a75217fe357.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Yisoong/ped#12

**Comment by Paulifyer** [comment]
Fixed by restricting command inputs in the regex pattern
