### ISSUE TITLE
[PE-D][Tester A] Edit feature bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T11-2/tp#148]
I have to add a space after 0 for the edit command to work

![image.png](https://raw.githubusercontent.com/KuanHsienn/ped/main/files/85488b91-985c-46f1-a50c-0e02dd485e72.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: KuanHsienn/ped#14

**Comment by raneeng** [comment]
cannot reproduce
