### ISSUE TITLE
[PE-D][Tester A] Bug in deletion

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-T11-2/tp#152]
Deletion of a module that does not exists result in program crash

![image.png](https://raw.githubusercontent.com/KuanHsienn/ped/main/files/5960b848-5be2-4de2-9d9a-fbbe809d83e1.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: KuanHsienn/ped#15

**Comment by raneeng** [comment]
no longer crashes but we can consider putting more helpful error messages
