### ISSUE TITLE
[PE-D][Tester A] Inaccuracy in class diagram

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T11-2/tp#157]
Unknown dotted arrow from above

![image.png](https://raw.githubusercontent.com/KuanHsienn/ped/main/files/2b423371-64f9-47db-a477-81f693b9ef59.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: KuanHsienn/ped#18

**Comment by frederickemerson** [comment]
fixed in pr #200
